name: Flutter Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: |
          cd escala_top
          flutter pub get
      
      - name: Build APK
        run: |
          cd escala_top
          flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: escala-top-app
          path: escala_top/build/app/outputs/flutter-apk/app-release.apk
